### PR TITLE
PAPRv10 adds waistband option and improves screw locations to fix gapping issue

### PR DESCRIPTION
**Pull request by inceptionev**
PAPRv10:
- Adds waistband mounting options
- New screw location addresses the gapping issue with the battery back
- Design optimized to reduce resin consumption
- Drain holes added to make cleaning out the screw threads easier
- USB PD and cable routing improved to make assembly less error-prone
- Outlet adapter improved for better mating to the blower outlet.
- Outlet key modified to increase tolerance
- Chitubox project files including supports and orientations added to documentation

This design has now been printed, assembled, and tested.  The documentation has been updated to reflect the Rev 10 assembly modifications.  This PR is now ready for review.

### CODE REVIEW

**Comment by inceptionev** [comment]
Added feature request: filter support on the front face to prevent the failure mode where the filter knocks into something, causing it to flex inward and break the bayonet mount.

**Review by martukas — CHANGES_REQUESTED** [review]
So, I think one of the screw holes is still missing a drain:
image

And the other question is:
Files appear to be duplicated, like for example `_PAPRv10-Body.chitubox` in both `sandbox` and under `release_candidates`. Is this intentional? This will blow up the repo and is kind of confusing.

**Comment by inceptionev** [comment]
- Drain hole is there, it's hidden there at the bottom where the wall meets the face.  I've tested-printed this and it does make cleaning it out much easier.
- At this moment, yeah those files in release candidates and sandbox are identical.  The sandbox however are meant to be living files.  So when experimenting with different things in the sandbox they can be built off those files rather than touching the ones in the release candidates folder.  I generally try to have the documentation link only to release candidate files.

**Review by martukas — APPROVED** [review]
Whoa! That is sneaky. Ok, now I see it :)

Ok, so this is good enough to get on the road.

I would highly suggest doing the file management a bit differently. We can use GH's "Releases" feature to take snapshots of the living files and even package releases for download.

Another thing that will help avoid repo blowup is to do a squash of commits before merging this. Otherwise, every intermediate version of the binary files in each commit will take up space.

**Comment by inceptionev** [comment]
sounds good, I've got some git-learning to do.  Squashing and merging.

**Pull request merged**
